# Generated by Django 4.2 on 2023-04-24 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('length', models.PositiveIntegerField(verbose_name='Длина')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Высота')),
                ('area', models.DecimalField(decimal_places=1, editable=False, max_digits=3, verbose_name='Площадь')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=50, verbose_name='Населенный пункт')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('short_description', models.CharField(max_length=50, verbose_name='Короткое описание')),
                ('temperature', models.IntegerField(verbose_name='Температура на складе')),
                ('main_image', models.ImageField(upload_to='', verbose_name='Основное изображение')),
                ('small_image', models.ImageField(upload_to='', verbose_name='Маленькое изображение')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('information', models.TextField(blank=True, verbose_name='Информация')),
                ('directions_to_storage', models.TextField(blank=True, verbose_name='Как добраться')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(verbose_name='Дата аренды')),
                ('rental_period_months', models.PositiveIntegerField(verbose_name='Срок аренды, месяцев')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.box', verbose_name='Бокс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storage.storage', verbose_name='Склад'),
        ),
    ]
