# Generated by Django 4.2 on 2023-04-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='end_rental_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания аренды'),
        ),
    ]
