# Generated by Django 4.2 on 2023-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Короткое описание'),
        ),
    ]
