# Generated by Django 4.2 on 2023-04-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storage_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='short_description',
            field=models.CharField(max_length=50, verbose_name='Короткое описание'),
        ),
    ]
