# Generated by Django 4.2 on 2023-04-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_storage_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Высота'),
        ),
    ]
