# Generated by Django 4.2 on 2023-04-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_box_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(verbose_name='Дата аренды')),
                ('rental_period', models.PositiveIntegerField(verbose_name='Срок аренды')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.box', verbose_name='Бокс')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
    ]
