# Generated by Django 4.2 on 2023-04-22 11:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0006_rental_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='rental_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rental_period',
        ),
        migrations.AddField(
            model_name='rental',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата окончания аренды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 22, 11, 12, 21, 205030, tzinfo=datetime.timezone.utc), verbose_name='Дата начала аренды'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='storage.box', verbose_name='Бокс'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
